### ISSUE TITLE
Properly sanitize extension names (and anything touching 'filename' structure for the zip)

### ISSUE THREAD

**Issue by mooeypoo** [mooeypoo/MWStew#12]
Extension names are used to output filenames in the zip, so they should be normalized. Anything with '../../' would probably screw up the zip structure. 

The good news is that this isn't really a security theat; the files and structure are stored in memory and the only thing that is written to the system is the zip file itself. This should still be fixed.

Hat tip @Catrope

**Comment by catrope** [comment]
https://github.com/mooeypoo/MWStew/blob/master/includes/Zipper.php#L15 trusts the extension name and uses it as part of the file name of the .zip. There's still a random component to the file name, but you could use ../../ injection to get the server to (attempt to) create that file in any directory you choose.
