### ISSUE TITLE
Don't create [MyExtension].php (or call wfLoadExtension there)

### ISSUE THREAD

**Issue by Krinkle** [mooeypoo/MWStew#20]
It's a bit confusing at the moment as it generates both a `[MyExtension].php` file (for old MediaWiki installs) and `extension.json` (for newer MediaWiki installs).

An extension can be loaded in LocalSettings.php as follows:

``` php
require_once "$IP/extensions/MyExtension/MyExtension.php";

# or

wfLoadExtension( 'MyExtension' );
// ^ loads "$wgExtensionDirectory/{name}/extension.json"
```

Having both is not uncommon for older extensions, however right now the generated `MyExtension.php` file doesn't actually work. It should contain a call to `wfLoadExtension( 'MyExtension' );` in order for a require_once on that file to actually load the extension.

However as better pattern for new extension, it probably makes more sense to remove creation of `MyExtension.php` entirely.

**Comment by mooeypoo** [comment]
Awesome, thank you for this! I removed the file completely.
