### ISSUE TITLE
extension.json references hook for JS test, but hook isn't defined

### ISSUE THREAD

**Issue by gi11es** [mooeypoo/MWStew#26]
![screenshot 2016-04-01 18 10 30](https://cloud.githubusercontent.com/assets/487183/14211130/1128a8cc-f835-11e5-80a3-f54b10c385e1.png)

![screenshot 2016-04-01 18 11 04](https://cloud.githubusercontent.com/assets/487183/14211141/1fdbc30e-f835-11e5-8850-9f4f2c11599b.png)

**Comment by mooeypoo** [comment]
Meh, another regression, the twig template should check for "parts.javascript" rather than "javascript"

Good catch, thanks!
