### ISSUE TITLE
Missing "AutoloadClasses" object

### ISSUE THREAD

**Issue by gi11es** [mooeypoo/MWStew#27]
I see this at the bottom of the extension.json:

![screenshot 2016-04-01 18 25 44](https://cloud.githubusercontent.com/assets/487183/14211505/297d6dc0-f837-11e5-912d-5fc1b4ad337c.png)

Which makes extensionprocessor unhappy:

![screenshot 2016-04-01 18 29 18](https://cloud.githubusercontent.com/assets/487183/14211612/aeb7ec40-f837-11e5-9409-549e2bd5adc8.png)

And I believe it's because that key/value pair should be inside AutoloadClasses, like so:

![screenshot 2016-04-01 18 31 36](https://cloud.githubusercontent.com/assets/487183/14211687/07dbbc7a-f838-11e5-8e85-63c1fe369ed3.png)

**Comment by mooeypoo** [comment]
Absolutely correct, whoops. I think this is a regression, too, I had the 'AutoloadClasses' object set up and when I migrated the code from using a template to outputting a complete json, I missed that part.

Fixing now, thanks!
