### ISSUE TITLE
ResourceLoaderTestModules should be an array and defined elsewhere

### ISSUE THREAD

**Issue by gi11es** [mooeypoo/MWStew#28]
Currently it's assigned a string value directly:

![screenshot 2016-04-01 18 33 47](https://cloud.githubusercontent.com/assets/487183/14211737/56a35d90-f838-11e5-9790-a5ab8c8c3f87.png)

which leads to mediawiki being unhappy:

![screenshot 2016-04-01 18 34 26](https://cloud.githubusercontent.com/assets/487183/14211750/647f0374-f838-11e5-9f5c-4dfc0d301046.png)

However, it's also defined in the wrong place, it should be inside Hooks:

![screenshot 2016-04-01 18 42 42](https://cloud.githubusercontent.com/assets/487183/14211999/8adde868-f839-11e5-9127-8d01076c4da8.png)

**Comment by mooeypoo** [comment]
Thanks for that! Fixing now.
