### ISSUE TITLE
info icons for hooks

### ISSUE THREAD

**Issue by eranroz** [mooeypoo/MWStew#37]
1. It would be nice if the info icons for hooks will link to MediaWiki wiki.
2. For other info icons that don't behave as link consider to add css rule: "cursor: help;" so it will be more clear you should just point the mouse over them :) 

Thank you for the great tool!

**Comment by mooeypoo** [comment]
I am actually planning to change the checkbox widgets to show the "help" line under the label so they're more accessible and obvious. Great idea about linking to the MW info!
