### ISSUE TITLE
Path for special page in extension.json doesn't match file path

### ISSUE THREAD

**Issue by BenignBeppe** [mooeypoo/MWStew#40]
The path for special page in _extension.json_ doesn't match the path to the special page file. E.g. when creating an extension with the name Wikispeech, the json variable will be `"SpecialWikispeech": "specials/SpecialPage.php"`, but the path to the actual file will be `specials/SpecialWikispeech.php`.

**Comment by mooeypoo** [comment]
As far as I could see, this depends on how many special pages you have in your extensions. If you only have one page, it's common to just call it SpecialPage.php. However, that might not be the **proper** way to call it, so your suggestion is absolutely valid.
